varNames <- c(
  "age",
  "marital",
  "education",
  "household_income",
  "residence",
  "duration_living",
  "duration_working",
  "primary_job",
  "working_hr_day",
  "working_hr_week",
  "workplace_toilet",
  "workplace_water",
  "age_menarche",
  "menstrual_regularity",
  "duration_menstrual",
  "missed_menstrual",
  "absorbent_type",
  "afford_pads",
  "pain_experience",
  "pain_severity_score",
  "frequency_of_pain",
  "reduced_work",
  "pain_urination",
  "frequent_urination",
  "lower_abdominal_pain",
  "lower_back_pain",
  "bloody_urine",
  "vaginal_discharge",
  "vaginal_odor",
  "genital_itching",
  "pain_intercourse",
  "reduced_fluid_intake",
  "urination_frequency",
  "urination_delay",
  "symptoms",
  "reasons",
  "place_care",
  "time_care",
  "satisfaction",
  "received_treatment"
)


c(
  "Age years",
  "Marital status",
  "Education level",
  "Monthly household income",
  "Place of residence",
  "Duration living in Dhaka years",
  "Duration working construction",
  "Primary job task",
  "Working hours per day",
  "Working days per week",
  "Workplace toilet availability",
  "Workplace drinking water access",
  "Age at menarche years",
  "Menstrual cycle regularity",
  "Duration of menstrual period days",
  "Missed menstrual period last 6 months",
  "Type of absorbent used",
  "Afford sanitary pads",
  "Menstrual pain experience",
  "Menstrual pain severity score",
  "Frequency of menstrual pain",
  "Missed or reduced work due to menstrual pain",
  "Burning or pain during urination",
  "Frequent or urgent urination",
  "Lower abdominal pain or discomfort",
  "Lower back or flank pain",
  "Cloudy dark or bloody urine",
  "Abnormal vaginal discharge",
  "Foul smelling vaginal odor",
  "Genital itching or irritation",
  "Pain or discomfort during sexual intercourse",
  "Reduced fluid intake during work",
  "Frequency of urination during work",
  "Delaying urination at work",
  "Sought medical care for urinary or reproductive symptoms",
  "Reasons for not seeking care",
  "Place of seeking care",
  "Time taken to seek care",
  "Satisfaction with healthcare services",
  "Received medication or treatment"
)



